service:
  name: bitly
  description: A bitly clone to shorten urls

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  role: arn:aws:iam::489728777585:role/bitly-lambda-role

functions:
  shorten:
    description: Receives a url and an optional custom id, returns a shortened bitly id or the custom id if available
    handler: handler.shorten
    events:
      - http:
          method: post
          path: shorten
          cors: true
  stats:
    handler: handler.stats
    events:
      - http:
          method: get
          path: stats/{id}
          cors: true
  redirect:
    handler: handler.redirect
    events:
      - http:
          method: get
          path: to/{id}
          cors: true